### PR TITLE
Adding new COMMON.md file

### PR DESCRIPTION
**Pull request by FranDepascuali**
The idea of this PR is to add a `COMMON.md` file for the talks/posts that are independent of a particular technology.

### CODE REVIEW

**Comment by FranDepascuali** [comment]
How do you think we should name it? @guidomb @epintos

**Comment by guidomb** [comment]
Maybe `General` or `Miscellaneous`?

**Comment by FranDepascuali** [comment]
Yeah, `Miscellaneous` describes it better but `General` is easier to understand. I like both. @epintos what do you think?

**Comment by epintos** [comment]
@FranDepascuali I think Common or General is okay

**Pull request merged**
